Agent:
    - prefLabel
    - lifespan
    - role
    - depiction
Concept:
    - prefLabel
#    - topConcept -- TODO: cannot currently be dereferenced
Place:
    - prefLabel
    - country
Timespan:
    - prefLabel
    - dateRange
